apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80  # Контейнер Nginx слушает порт 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: NodePort  # Указываем NodePort для проброса порта
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80          # Внутренний порт ClusterIP
    targetPort: 80    # Порт контейнера, на который идет трафик
    nodePort: 30000   # Пробрасываем порт кластера (Kind настроен на 30000)

